### PR TITLE
Raise the open fd limit to the maximum allowed

### PR DESCRIPTION
**Pull request by doublesharp**
https://github.com/bitcoin/bitcoin/pull/11785

Fixes errors with rapid RPC calls exhausting queue.

### CODE REVIEW

**Comment by sidhujag** [comment]
utACK

**Comment by sidhujag** [comment]
We should confirm that we really need this once more @doublesharp

**Comment by doublesharp** [comment]
Testing with Syscoin Core version v3.0.5.0-f1e00c93f, rapid requests to `aliasbalance`. Started with `-reindex` and allowed to sync before starting test.

Two successful runs then:

```
> node stakes.js 
1 'tesla' { balance: 0 }
2 'shop.cn' { balance: 0.00052294 }
3 'tehran.sex' { balance: 0.00051848 }
4 'converse' { balance: 0 }
5 'europe.us' { balance: 0.00051997 }
6 'bench' { balance: 0 }
7 'mixer' { balance: 0 }
8 'drvosjeca' { balance: 0 }
9 'bartmul' { balance: 615.00004125 }
undefined:1
Work queue depth exceeded
^

SyntaxError: Unexpected token W in JSON at position 0
    at JSON.parse (<anonymous>)
    at obfuscateRequest (/Workspaces/syscoin/syscoin-core/dist/src/logging/request-obfuscator.js:97:23)
    at obfuscate (/Workspaces/syscoin/syscoin-core/dist/src/logging/request-obfuscator.js:126:3)
    at /Workspaces/syscoin/syscoin-core/dist/src/logging/request-logger.js:24:36
    at Request.<anonymous> (/Workspaces/syscoin/syscoin-core/node_modules/@uphold/request-logger/src/index.js:33:9)
    at Request.emit (events.js:185:15)
    at Request.<anonymous> (/Workspaces/syscoin/syscoin-core/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/Workspaces/syscoin/syscoin-core/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

Restarting without reindex fails with different aliases passing
```
> node stakes.js 
1 'tesla' { balance: 0 }
2 'shop.cn' { balance: 0.00052294 }
3 'europe.us' { balance: 0.00051997 }
4 'tehran.sex' { balance: 0.00051848 }
5 'converse' { balance: 0 }
6 'bench' { balance: 0 }
7 'alias.peg' { balance: 0.00051997 }
undefined:1
Work queue depth exceeded
^

SyntaxError: Unexpected token W in JSON at position 0
    at JSON.parse (<anonymous>)
    at obfuscateRequest (/Workspaces/syscoin/syscoin-core/dist/src/logging/request-obfuscator.js:97:23)
    at obfuscate (/Workspaces/syscoin/syscoin-core/dist/src/logging/request-obfuscator.js:126:3)
    at /Workspaces/syscoin/syscoin-core/dist/src/logging/request-logger.js:24:36
    at Request.<anonymous> (/Workspaces/syscoin/syscoin-core/node_modules/@uphold/request-logger/src/index.js:33:9)
    at Request.emit (events.js:185:15)
    at Request.<anonymous> (/Workspaces/syscoin/syscoin-core/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/Workspaces/syscoin/syscoin-core/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

**Comment by doublesharp** [comment]
Testing with Syscoin Core version v3.0.5.0-ba8f877f1 I was able to overload the RPC worker queue but increasing the number of workers allowed it to scale much higher than unpatched. Seems to be functioning better although there was a failure.

```Elapsed ms 26207
Total Aliases 13267

**Comment by sidhujag** [comment]
perhaps using aliasbalancemulti is something that we will need as the number of aliases grow for subsequent airdrops we may run into this issue even with patched libevent+client side fd patches

**Comment by sidhujag** [comment]
Whats the verdict @doublesharp I since have added aliasbalancemulti so do we want to use that or add this as well?

**Comment by doublesharp** [comment]
This seemed to help but I was still able to reproduce the issue so I would hold off on it pending more testing and debugging. Adding -rpcworkqueue=1000000 seems to help.

**Pull request closed without merging**
