### PR TITLE
full version filenames

### PR DESCRIPTION
**Pull request by einalex**
This pull request makes three little changes that give us X.X.X.X style version numbers across the project including in generated files.
This allows us to unmistakeably identify files and programs.
This also makes it easier to automatically handle bundled binaries.

### CODE REVIEW

**Comment by willyko** [comment]
utACK

**Comment by sidhujag** [comment]
@einalex we generally merge from dev-3.x but I will approve this one

**Review by sidhujag — APPROVED** [review]

**Comment by alex-quin-gabriel** [comment]
@sidhujag dev-3.x was in the state prior to your merge into master for 3.0.5 that's why I created it against master. Can you in the future also merge master into dev-3.x after each version release?

**Comment by sidhujag** [comment]
Dev-3.x is always up-to-date with master after a release, we generally merge to dev-3.x first then to master. I think we should rebase this to dev-3.x so it remains in sync with master.

**Comment by sidhujag** [comment]
Please rebase with dev-3.x

**Comment by doublesharp** [comment]
We can cherry-pick this in -

git remote add einalex https://github.com/einalex/syscoin.git

git fetch einalex

git cherry-pick a862b7dbf76dce6aa1cfb8bb6a1b0609509efb5a

**Comment by sidhujag** [comment]
pulled in with 05a6ec5a3fe7030b59b53b797cf59399f02038da

**Pull request closed without merging**
