### PR TITLE
Dev 4.x

### PR DESCRIPTION
**Pull request by sidhujag**
Syscoin 4 merge to master.

-Assets (with hardened ZDAG protocol)
-Sysethereum bridge (ability to trustlessly move across to another blockchain, disabled until block height 51000 at which point it will automatically start validating bridge transactions)
-New masternode ping protocol to avoid network congestion around pinging every masternode. Much more efficient.

Fixed many bugs and issues, improvements to the codebase. Re-based off of latest Bitcoin 0.19x and keep up-to-date with master branch.

### CODE REVIEW

**Review by willyko — DISMISSED** [review]
ACK

**Review by dwasyluk — DISMISSED** [review]
Looks super!

**Review by Keyare — COMMENTED** [review]
Goes well with beer

**Review by dwasyluk — DISMISSED** [review]

**Review by willyko — APPROVED** [review]

**Review by Keyare — COMMENTED** [review]
APP

**Pull request merged**
