### PR TITLE
Fix crash bug with duplicate inputs within a transaction

### PR DESCRIPTION
**Pull request by CryptoDJ**
Commit: https://github.com/bitcoin/bitcoin/commit/b8f801964f59586508ea8da6cf3decd76bc0e571
PR: https://github.com/bitcoin/bitcoin/pull/9049

### CODE REVIEW

**Comment by CryptoDJ** [comment]
I see you already made the change in dev-3.x-assets-escrow.  closing PR.

**Comment by jnessbcf** [comment]
Actually I’d reopen it - ideally we want bug fixes and feature additions to
be separate anyway...

**Review by jnessbcf — APPROVED** [review]

**Review by Keyare — APPROVED** [review]

**Review by radubcf — APPROVED** [review]

**Comment by doublesharp** [comment]
closing/opening to trigger travis build

**Comment by doublesharp** [comment]
closing/opening to trigger travis build

**Pull request closed without merging**
