### PR TITLE
Sys 320 accept options

### PR DESCRIPTION
**Pull request by eugenekatsov**
From https://github.com/bitcoin/bitcoin/pull/12040 
Specific to the use case of rpc to localhost
The only code left out of the original bitcoin pr is setting and checking rpccors domain from config
The test is specific to syscoin rpc-tests

### CODE REVIEW

**Comment by willyko** [comment]
if you rebase your branch to the latest 3.2.0, travis should pass now

**Comment by sidhujag** [comment]
NACK I need to see the rpccors config variable which should be disabled by default. I don't see that code anywhere. If you took code from bitcoin please port it over in full.

**Comment by eugenekatsov** [comment]
Hey Jag,

I will update the code and have the rpccors variable disabled.

**Comment by eugenekatsov** [comment]
Closing this as I needed to set the changes on 3.1.5 PR #294

**Pull request closed without merging**
