### PR TITLE
Create microftech ccpp.yml

### PR DESCRIPTION
**Pull request by microftech65**
https://GitHub.com/jbeder/yaml-cpp

### CODE REVIEW

**Comment by microftech65** [comment]
Reviewed  Merger bitcoin#15794:docs:Clarify PR
no: milestone

**Comment by microftech65** [comment]
Merge for bitcoin#15694: docs: Clarify PR has checks

**Comment by microftech65** [comment]
microftech ccpp.yml #377  has been reviewed

**Comment by sidhujag** [comment]
Explain this @microftech65

**Comment by sidhujag** [comment]
lack of substance, open again with explanation

**Pull request closed without merging**
